### ISSUE TITLE
How to work with send_custom_alerts

### ISSUE THREAD

**Issue by JustLike420** [TheRealMizAL/DaLaS#2]
I use it, request have 201 status. Good, but nothing happened. 
What i need to do in DonationAlerts to show custom message on stream?

**Comment by TheRealMizAL** [comment]
@JustLike420 hi!

First you should add new variation to the group that you want to use. Then set alert type as "Custom alerts". After that everything should work

**Comment by JustLike420** [comment]
I have such alert with "Custom alerts" type.

![image](https://user-images.githubusercontent.com/44843816/225047126-cb707d47-2ca6-4495-85df-4fcb0e9ea8af.png)

when i send it, i get such response:
{"data":{"id":2391275,"external_id":"42","header":"13usd","message":"test message","image_url":null,"sound_url":null,"is_shown":1,"created_at":"2023-03-14 15:11:07","shown_at":null}}

but nothing hapened :(

**Comment by TheRealMizAL** [comment]
@JustLike420 kinda strange because everything seems right. Try this steps:

1. Check the user. After launching, Dalas request "user/oauth" method so you can check that you use the right user

2. Ensure that you recieved an alert (smth like this)
<img width="368" alt="image" src="https://user-images.githubusercontent.com/50375436/226426713-d02b6e59-170b-4289-a32d-038be7d10b08.png">

3. If you recieved notification from the previous step, check your widget settings. Seems like you've configured them correctly, but check them anyways

4. Launch the group and then run your code. If previous steps were passed, you will see your alert
<img width="745" alt="image" src="https://user-images.githubusercontent.com/50375436/226431438-aa136b37-3562-40bd-b50a-f939cd078833.png">

5. Check your streaming app. Ensure, that you use the right link, widget is enabled, placed on the top of the screen and so on

6. At this step everything should be ok, If it's not, it remains you only to pray 🤡

**Comment by JustLike420** [comment]
ty bro!
